const hint = {
    pikachu : "Goddess of knowledge",
    chansey : "Book deposit station",
    charmender : "Off Road Car",
    caterpie : "Food time",
    charizard : "Money",
    clefairy : "Recruitment",
    diglett : "Saplings",
    ditto : "Football, basketball, all equipment",
    dragonite : "Theatre",
    eevee : "The big boss",
    ekans : "What is that collage famous for",
    gengar : "8085 & 8086",
    geodude : "City of Energy",
    gyarados : "Wood you like it?",
    jigglypuff : "File file file........ :(",
    jynx : "In and out everyday stories",
    koffing : "Park not for human",
    lapras : "Ice Cream",
    machamp : "Oh God this again",
    magikarp : "This is a work of art not for fools!",
    snorlax : "My fav game football what’s your?",
    meowth : "More!! Beautiful haha",
    mew : "Science I hate this but girl. ;). Haha",
    mewtwo : "My love letter did you get it ufff ",
    mr_mime : "Public quarries?",
    bellsprout : "I got hurt :(",
    butterfree : "Second famous of this college",
    oddish : "Warriors :)",
    onix : "350 cc",
    muk : "I am still single got love to but anyway sit at shakuntalam",
    ninetales : "Solar power I like it",
    persian : "Park for humans but to be alone"
}

module.exports = hint;