const location = {
    saraswati_mata : "With wisdom and artistry, I hold my sway, A symbol of knowledge, I guide your way. Amidst the campus, where learning is embraced, Find me, and your treasure will be placed",
    library : "Within a fortress of bound knowledge, I reside, where countless stories and truths do hide. A reticent realm where words and worlds take flight",
    supra_quater : ": I'm found where engines roar, On campus grounds, we test and explore. With wheels that grip and engines that hum, In mud and dirt, we surely have fun",
    cafeteria : "Within a realm of sustenance and shared delight, Where sustenance fuels both day and night, Amidst the noises of chit-chat, your hidden gem rests in this bustling space",
    bank : "A place of finance, where numbers dance in rows, Where investments grow and knowledge flows. In a realm of transactions, wealth's embrace, Your treasure awaits in this guarded space",
    tpo : "In the nexus of dreams and career's race, Where opportunities await and futures take their place. Within these walls, where aspirations take flight, Your treasure's concealed, out of sight",
    nursery : "Seek the cradle of growth where tiny buds reside, In a realm where chlorophyll and sunlight coincide. To find your prize in this lush and tranquil space, Decipher this riddle with a keen embrace",
    sports_room : "To claim your prize in this competitive race, search for the arena where strength takes its stance, Where victories are celebrated in every advance",
    auditorium : " Look to the spot where stories are told, tis the place where your journey unfolds, in the echoes there’s a treasure it holds",
    vc_office_front : "In the heart of the campus, where decisions are made, Leadership resides in the shade. Amidst the corridors of power and grace, Your treasure is hidden in this important place",
    computer_department : "whether its work or play, some may say im the biggest part of your day. In the den of toppers, silicon’s domain, can you discern where knowledge reigns?",
    electronics_department : "In a world of electrons' ceaseless flight, Where knowledge sparks, illuminating the night. Within this fortress of circuits and space, Your treasure's concealed in an elusive gaze",
    electrical_department : "Search for the sanctuary where electrons play, In the heart of innovation, day by day. To seize your prize in this charged-up place, Decode this riddle with a spark of grace",
    carpenter_room : "Seek the place where artisans hone their craft, Where tools make shapes and goods draft. To uncover your prize in this place, Solve this riddle with a crafty trace",
    mechanical_workshop : "In a world of precision, where cogs interlace, Engineering marvels take shape with skill and grace. Amidst the labyrinthine machinery's embrace, Your treasure's hidden in this tiring space",
    golden_jubilee_gate : "Search for the portal where time's passage unfurls, In the structure that marks anniversaries and pearls. To unveil your prize at this commemorative place, Solve this riddle, and don't underestimate",
    staff_parking : "In rows and lots, I neatly stand. From morning's light till the day is done, I provide a spot for everyone",
    mother_dairy : "The place is small but full of delight, it refreshes you after the day's plight. Ask your seniors for a treat and see them fright",
    temple : "In a realm where silence reigns, and reverence is near, Amidst the whispers that only few can hear. To reveal your prize in this ethereal embrace, Meditate on this riddle with tranquil grace",
    srijan_quaters : "Search for the spot where imagination takes flight, In a realm where colours and visions unite",
    cv_raman : "Seek the portal where scholars delve, In a universe where particles and mysteries themselves. Many bunk their classes to wander around this place",
    post_box : "I'm an old agent of communication, guarding secrets close to the heart. Amidst the streetscape, where life's rhythms race, Your treasure's concealed in my embrace",
    public_affair_cell : "Amidst the web of information's grand design, Where narratives are spun, and truths entwine. In the heart of communication's lively embrace, Decipher this riddle with a journalist's grace",
    medical_room : "I'm a place of relief when you're feeling low, where your ailments will soon go. With shelves of cures, both natural and sound, In this sanctuary, solutions are found",
    mechanical_department : "Where gears turn silently, and metal whispers truth, In a place where innovation blooms and engineers find their youth",
    soldier : " In stoic vigil, a sentinel stands tall and true, Guarding the legacy of valour in the morning dew",
    royal_enfield : "In a realm of steel horses and engines that roar, Amidst the tools and grease, where legends galore",
    lovers_wall : "this is where most want to be, some grab the spot and some envy, it all comes down to the way you see",
    renewable_energy_lab : " In this place, we innovate and explore, Sustainable sources we all adore. Batteries store what nature provides, In this eco-friendly space, progress abides",
    mba_park : "on the far edge close to those mountains, it’s a refuge from hustle,a serene embrace",
    ucc : "I'm where wires and screens abound, In a campus hub where knowledge is found. Students and staff, they all rely, On me to help them reach the sky",
    messi : "Seek the icon where jerseys roar his name, In a stadium's embrace, his glory's the flame. Think of the maestro in this thrilling chase",
    samarpan_quaters: "I am very blue, But I'm not sad. A creature of elegance , I take my stand . But in this riddle's maze, I conceal my name, A puzzle to solve, a cryptic claim."
}

const riddle = {
    'pikachu' : location.saraswati_mata,
    'chansey' : location.library,
    'charmender' : location.supra_quater,
    'caterpie' : location.cafeteria,
    'charizard' : location.bank,
    'clefairy' : location.tpo,
    'diglett' : location.nursery,
    'ditto' : location.sports_room,
    'dragonite' : location.auditorium,
    'eevee' : location.vc_office_front,
    'squirtle' : location.ucc,

    'ekans' : location.computer_department,
    'gengar' : location.electronics_department,
    'geodude' : location.electrical_department,
    'gyarados' : location.carpenter_room,
    'jigglypuff' : location.mechanical_workshop,
    'jynx' : location.golden_jubilee_gate,
    'koffing' : location.staff_parking,
    'lapras' : location.mother_dairy,
    'machamp' : location.temple,
    'magikarp' : location.srijan_quaters,
    'snorlax' : location.messi,

    'meowth' : location.samarpan_quaters,
    'mew' : location.cv_raman,
    'mewtwo' : location.post_box,
    'mr_mime' : location.public_affair_cell,
    'bellsprout' : location.medical_room,
    'butterfree' : location.mechanical_department,
    'oddish' : location.soldier,
    'onix' : location.royal_enfield,
    'muk' : location.lovers_wall,
    'ninetales' : location.renewable_energy_lab,
    'persian' : location.mba_park
}

module.exports = riddle;